Support oauth authentication (private preview for AWS)
databricks/databricks-sql-cli pull request #41
Opened 2023-01-04 01:10 UTC by jackyhu-db

Add a comand line flag `--oauth` to use OAuth for authentication ( OAuth Authorization Code flow with PKCE).

Usage:

  ```bash
  dbsqlci --hostname <hostname> --http_path <http_path> --oauth
  ```

OAuth authentication can also be turned on by setting `auth_type` to `databricks-oauth` in config file

```
[credentials]
host_name = "xxx.cloud.databricks.com"
http_path = "/path/to/endpoint"
access_token=""
auth_type="databricks-oauth"
```

**Note**: OAuth support in Databricks is still **Private Preview** and only works in AWS.

2023-01-11 16:00 UTC, susodapop requested changes
I have a few questions. Overall looks great!

2023-01-11 16:00 UTC, susodapop commented on dbsqlcli/main.py
> +def apply_credentials_from_cfg(hostname, http_path, access_token, auth_type, cfg):
nit: update the docstring

2023-01-11 16:00 UTC, susodapop commented on dbsqlcli/sqlexecute.py
> +class OAuthPersistenceCache(OAuthPersistence):
To confirm: this cache will expire when the program exits? Meaning that the user will re-auth the next time they run `dbsqlcli`?

2023-01-11 16:00 UTC, susodapop commented on pyproject.toml
> +version = "0.1.5"
We'll handle the version bump in a separate PR.

2023-01-11 16:00 UTC, susodapop commented on dbsqlcli/main.py
> +        auth_type=AuthType.DATABRICKS_OAUTH.value if oauth else None,
For clarity I think we should make the default `'pat'` because in the absence of an OAuth configuration, the authentication type is to use a personal access token. `auth_type==None` suggests that no authentication will be performed.

2023-01-11 16:00 UTC, susodapop commented on pyproject.toml
> +numpy = [
Why does this need to be specified here? These definitions appear to be borrowed from the `databricks-sql-connector` library. But since `dbsqlcli` already depends on that library, then this installation logic will already be applied during installation of that dependency.

2023-01-11 21:32 UTC, jackyhu-db commented on dbsqlcli/sqlexecute.py
> +class OAuthPersistenceCache(OAuthPersistence):
Correct. This is in-memory cache, token is not persisted anywhere.

2023-01-11 21:33 UTC, jackyhu-db commented on pyproject.toml
> +version = "0.1.5"
Good to know, I will revert this change.

2023-01-11 21:34 UTC, jackyhu-db commented on dbsqlcli/main.py
> +        auth_type=AuthType.DATABRICKS_OAUTH.value if oauth else None,
OK. I will update it.

2023-01-13 04:05 UTC, susodapop commented on pyproject.toml
> +numpy = [
After discussion with @jackyhu-db we've determined that the `numpy` spec really _does_ need to be highlighted here, even though it duplicates the same spec that appears in the `databricks-sql-connector``pyproject.toml`. Unfortunately, Poetry isn't able to gather this dependency spec during its dependency resolution so the repetition is required.

2023-01-16 17:34 UTC, jackyhu-db commented on dbsqlcli/main.py
> +def apply_credentials_from_cfg(hostname, http_path, access_token, auth_type, cfg):
updated.

2023-01-16 17:47 UTC, jackyhu-db commented on dbsqlcli/main.py
> +        auth_type=AuthType.DATABRICKS_OAUTH.value if oauth else None,
@susodapop PySQL infers `pat` or `user/pass` if `auth_type` is not specified (see [here](https://github.com/databricks/databricks-sql-python/blob/main/src/databricks/sql/auth/auth.py#L13)). So I changed the code to not set `auth_type` if oauth flag is not set.

2023-01-19 17:20 UTC, susodapop approved these changes
LGTM

2023-01-19 17:21 UTC, merged